- name: Deploy redmine app to hosts
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install pip package manager to get python modules
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Run Redmine container and connect it to an existing db
      community.docker.docker_container:
        name: redmine-postgre
        image: redmine
        published_ports:
         - 3000:3000
        restart_policy: always
        restart: yes
      environment: "{{ env_vars }}"

- name: Setup Datagog health checks on webservers
  hosts: webservers
  gather_facts: no
  remote_user: root
  roles:
    - { role: datadog.datadog, become: yes }
